{% set version = "4.18" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: 33ee8ceb63f1db61cce8b5c800c531e1a61023ac5488ccde2ba574a85be00a85

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyreadline  # [win]

test:
  imports:
    - humanfriendly

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: 'Human friendly output for text interfaces using Python.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
