{% set version = "4.9" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: c2c98143f0b01fc65fee6b6a0436b01d8c77b55cad6ae7bf268e1fb586aae6b7

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - humanfriendly

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  summary: 'Human friendly output for text interfaces using Python.'

extra:
  recipe-maintainers:
    - ocefpaf
