{% set version = "4.10" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: 30eeab45eb22eb95e1f7d1e2657d381fa9b2b3f28613b942e5935dc90bb5a6c1

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - humanfriendly
  commands:
    # the build workers do not have a fully functional terminal which hangs
    # which command.
    - humanfriendly --help  # [not unix]

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  summary: 'Human friendly output for text interfaces using Python.'
  description: |
    The functions and classes in the humanfriendly package can be used to make text interfaces more user friendly. 
  doc_url: https://humanfriendly.readthedocs.io/en/latest/
  dev_url: https://github.com/xolox/python-humanfriendly
  doc_source_url: https://github.com/xolox/python-humanfriendly/tree/master/docs

extra:
  recipe-maintainers:
    - ocefpaf
