{% set version = "8.1" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: 25c2108a45cfd1e8fbe9cdb30b825d34ef5d5675c8e11e4775c9aedbfb0bdee2

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyreadline  # [win]
    - monotonic  # [py2k]

test:
  imports:
    - humanfriendly
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: Human friendly output for text interfaces using Python.

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
