{% set version = "4.15" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: f34f504dd063c2a9bd095fffbce79a639bd6eb067bd6b1318d7b8e67e71a0147

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - humanfriendly

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  summary: 'Human friendly output for text interfaces using Python.'

extra:
  recipe-maintainers:
    - ocefpaf
