{% set version = "9.2" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: f7dba53ac7935fd0b4a2fc9a29e316ddd9ea135fb3052d3d0279d10c18ff9c48

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pyreadline  # [win]
    - monotonic  # [py2k]

test:
  imports:
    - humanfriendly
  requires:
    - pip
  commands:
    - pip check
    # the build workers do not have a fully functional terminal which hangs
    # which command.
    - humanfriendly --help  # [not unix]

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Human friendly output for text interfaces using Python.'
  description: |
    The functions and classes in the humanfriendly package can be used to make text interfaces more user friendly. 
  doc_url: https://humanfriendly.readthedocs.io/en/latest/
  dev_url: https://github.com/xolox/python-humanfriendly
  doc_source_url: https://github.com/xolox/python-humanfriendly/tree/master/docs

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
