{% set version = "4.8" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  fn: humanfriendly-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: d0e74171b87318a94b99520e4f0c5651e944b5f11d696c46be3330bb82b85300

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - humanfriendly
  commands:
    # the build workers do not have a fully functional terminal which hangs
    # which command.
    - humanfriendly --help  # [not unix]

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  summary: 'Human friendly output for text interfaces using Python.'
  description: |
    The functions and classes in the humanfriendly package can be used to make text interfaces more user friendly. 
  doc_url: https://humanfriendly.readthedocs.io/en/latest/
  dev_url: https://github.com/xolox/python-humanfriendly
  doc_source_url: https://github.com/xolox/python-humanfriendly/tree/master/docs

extra:
  recipe-maintainers:
    - ocefpaf
