{% set version = "4.18" %}

package:
  name: humanfriendly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanfriendly/humanfriendly-{{ version }}.tar.gz
  sha256: 33ee8ceb63f1db61cce8b5c800c531e1a61023ac5488ccde2ba574a85be00a85

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - humanfriendly = humanfriendly.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyreadline  # [win]

test:
  imports:
    - humanfriendly
  commands:
    # the build workers do not have a fully functional terminal which hangs
    # which command.
    - humanfriendly --help  # [not unix]

about:
  home: https://humanfriendly.readthedocs.org
  license: MIT
  summary: 'Human friendly output for text interfaces using Python.'
  description: |
    The functions and classes in the humanfriendly package can be used to make text interfaces more user friendly. 
  doc_url: https://humanfriendly.readthedocs.io/en/latest/
  dev_url: https://github.com/xolox/python-humanfriendly
  doc_source_url: https://github.com/xolox/python-humanfriendly/tree/master/docs

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
