# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rUDzE+UKktfWCdm7gBsfD0U/10bd9Dff8TQ3do9Z3jRTkOKmMYE8WSU53jLj6pH6OxVC+7sDYGIzb6XnHtjVZE8tee0L27QjCozuxlmI6iwpKYCffh1241S+2RbKOz1GLe80l+idX4bnuYT1MZp7BZ6mR5GVZFXg1sfM6SxNyI9/sz3FUEiO/Bm6GVo2j1FTPDRqvurG8P2jJYD36ZZ7xtjDuJ9oMzAyMala4zuUgR7F0LYFhA6cwnfkCPrmAGlshHBvHhdCWkUZtfuE2S/XhgHblII5oX57xeT+WVCRshlYlLk757ajyiuFvwX/s7fYCYEcoa2Cw2gZ85x44MPJMzv+9ZCuzoBBGIQOBt9KTn2T5K+EKcAOc/QOIc2RsVLaDciMXFxRbjN1jMFUpN0StJjY7O/25JkOoC3447GE5GIzs2nuEnKW6kTh8kXrwTrykTFLZhOzsnn8c5s5wbaYyhvgkRccC+fiNrLIzQQuS17seOsE8+q0OladtNy3Gp0TCe6SPieEXl8duuIEoGxoJN1BESfjfuG7sT/pXTfbub4WN5REMpKQxnWTVDiNP7F99dsg+0wZNocM3SK0W1W3+aXxlqVl9voFTal543b0a2PzyFg+1X1Rm16/Md9cVp+yAPWPpOZcRUmx063inc9k15HFKcPleB/z/FQoipXZMqs="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
