travis:
  secure:
    BINSTAR_TOKEN: rUDzE+UKktfWCdm7gBsfD0U/10bd9Dff8TQ3do9Z3jRTkOKmMYE8WSU53jLj6pH6OxVC+7sDYGIzb6XnHtjVZE8tee0L27QjCozuxlmI6iwpKYCffh1241S+2RbKOz1GLe80l+idX4bnuYT1MZp7BZ6mR5GVZFXg1sfM6SxNyI9/sz3FUEiO/Bm6GVo2j1FTPDRqvurG8P2jJYD36ZZ7xtjDuJ9oMzAyMala4zuUgR7F0LYFhA6cwnfkCPrmAGlshHBvHhdCWkUZtfuE2S/XhgHblII5oX57xeT+WVCRshlYlLk757ajyiuFvwX/s7fYCYEcoa2Cw2gZ85x44MPJMzv+9ZCuzoBBGIQOBt9KTn2T5K+EKcAOc/QOIc2RsVLaDciMXFxRbjN1jMFUpN0StJjY7O/25JkOoC3447GE5GIzs2nuEnKW6kTh8kXrwTrykTFLZhOzsnn8c5s5wbaYyhvgkRccC+fiNrLIzQQuS17seOsE8+q0OladtNy3Gp0TCe6SPieEXl8duuIEoGxoJN1BESfjfuG7sT/pXTfbub4WN5REMpKQxnWTVDiNP7F99dsg+0wZNocM3SK0W1W3+aXxlqVl9voFTal543b0a2PzyFg+1X1Rm16/Md9cVp+yAPWPpOZcRUmx063inc9k15HFKcPleB/z/FQoipXZMqs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
