travis:
  secure:
    BINSTAR_TOKEN: L/BduIOP4cPTJPxYJH1mDZNh1n+HY1SMYAg9NwdjfFj6Aw7WrAD8SVnnRe1RgTxSwbWUzhQWAozPEIs1kM+bBihX9wcF0EqY4f/cbXXdbjsiN89grkzakmk0feovj6AJs9cF1KZqqamhukX07+UNJ1Se8LojGcjAjrFOTCbpvJ5hisEo2O6tMdKHmgjrMoqjolv7NAJodEjKMnsS4PyriSbBQXL8+q0T23WbjCRcum43Aw60B+5eg/b6qkmVrFEXyJaMQ2CUdH1xECvg1UcT2UCofHUGNa+w14EkNvr9/dAdBsYaqSucjvtPPLwGYclnFuyH2jT13d3Xujji8TKufHrLXVkHr+842Wo/YR1U+LOme87YInU2dKzyLKJhBTKlBCvv8qXjjoyKpZ44eoWcMTt8rXL+s/4sG+8xN8CcS4dBNaC7oQyuT1B+G/xEiulxX32V+SIM1Bau0ZzJ8Z3QNpnjyfLOqsydAfhHW/qIBlx6Ox9AngOr2N/N/RVBIHHuwkowuvC1tWEvCOrTGYET/VSlEODIXxYO48H9vLNROFlNYnfaYoZUOrbZtNFOAuSvX4UnIldqQY0OkRWg9A1dbFZ24iy/GjtNYP/MH3Y3haur3ze2bnmBzqmYVaUZYMHE4dFcfxFS0iMCNUI2lpB0tzo3kFzoQakgPme/E4n6/Ow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
